---

- name: 'DOCKER SERVICE | Deploy untemplated files'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ _docker_service_files | default([]) }}"


- name: 'DOCKER SERVICE | Deploy configuration files templates'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ _docker_service_templates | default([]) }}"


- name: 'DOCKER SERVICE | Configure Docker registries credentials'
  docker_login:
    email: "{{ item.email | default(omit) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    registry_url: "{{ item.registry_url }}"
  loop: "{{ _docker_registries | default([]) }}"
