---

- name: 'DOCKER SERVICE | Deploy untemplated files'
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ _docker_service_files | default([]) }}"


- name: 'DOCKER SERVICE | Deploy docker-compose.override.yml'
  template:
    src: 'templates/docker-compose.override.yml.j2'
    dest: "{{ ansistrano_release_path.stdout }}/docker-compose.override.yml"
  when: "_docker_compose_override | length > 0"


- name: 'DOCKER SERVICE | Deploy configuration files templates'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ _docker_service_templates | default([]) }}"


- name: 'DOCKER SERVICE | Configure Docker registries credentials'
  docker_login:
    email: "{{ item.email | default(omit) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    registry_url: "{{ item.registry_url }}"
  loop: "{{ _docker_registries | default([]) }}"
